sudo: required
dist: bionic

addons:
  ssh_known_hosts: 
    - jc0b.computer:4000
    - 185.87.187.226:4000

before_install:
- curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep "browser_download_url.*64bit.deb" | cut -d '"' -f 4 | wget -qi -
- rm hugo_extended*.deb
- sudo dpkg -i hugo_*.deb


script:
- hugo

before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avz --delete -e 'ssh -p 4000' $TRAVIS_BUILD_DIR/public/ jacobs1q@jc0b.computer:bsc.jc0b.computer/
  on:
    branch: master

#discord channel integration   
after_success:
  - wget http://assets.jacobsburley.com/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget http://assets.jacobsburley.com/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL