sudo: required
dist: bionic
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out deploy_rsa -d
- curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep "browser_download_url.*64bit.deb" | cut -d '"' -f 4 | wget -qi -
- rm hugo_extended*.deb
- sudo dpkg -i hugo_*.deb
script:
- hugo
